import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import styles from "./page.module.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"/>
        <meta name="viewport" content="width=device-width"/>
        <title>채팅방</title>
        {/* 사전순으로 써야된다고? */}
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=call,chat,chat_add_on,group,person_add,videocam" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.inner}>
          {children}
        </div>
      </body>
    </html>
  );
}
